apiVersion: batch/v1
kind: CronJob
metadata:
  name: gsheets-app
spec:
  schedule: "*/2 * * * *" # every day at 7:00 AM cluster time
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: gsheets-app
        spec:
          restartPolicy: OnFailure
          containers:
            - name: gsheets-app
              image: infinitiq502004/family-map:1.1.6
              imagePullPolicy: IfNotPresent
              env:
                - name: APP_ENV
                  value: kubernetes
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: /var/secrets/google/service_account.json
              volumeMounts:
                - name: google-creds
                  mountPath: /var/secrets/google
                  readOnly: true
              securityContext:
                privileged: true
          volumes:
            - name: google-creds
              secret:
                secretName: google-service-account